"""プロセスアーキテクチャ基盤.

基盤クラス群は xkep_cae_deprecated/process/ から暫定 re-export。
strategies/ 配下は新規実装に順次置き換える。
"""

from xkep_cae_deprecated.process import (  # noqa: F401
    AbstractProcess,
    AssembleCallbacks,
    BatchProcess,
    BoundaryData,
    CompatibilityProcess,
    ContactFrictionInputData,
    ContactSetupData,
    ExecutionContext,
    MeshData,
    NodeType,
    PostProcess,
    PreProcess,
    ProcessMeta,
    ProcessMetaclass,
    ProcessNode,
    ProcessRegistry,
    ProcessRunner,
    ProcessTree,
    SolverProcess,
    SolverResultData,
    SolverStrategies,
    StrategySlot,
    VerifyInput,
    VerifyProcess,
    VerifyResult,
    binds_to,
    collect_strategy_slots,
    collect_strategy_types,
    default_strategies,
)

__all__ = [
    "AbstractProcess",
    "ProcessMeta",
    "ProcessMetaclass",
    "PreProcess",
    "SolverProcess",
    "PostProcess",
    "VerifyProcess",
    "BatchProcess",
    "CompatibilityProcess",
    "binds_to",
    "ProcessTree",
    "ProcessNode",
    "NodeType",
    "MeshData",
    "BoundaryData",
    "ContactSetupData",
    "AssembleCallbacks",
    "ContactFrictionInputData",
    "SolverResultData",
    "SolverStrategies",
    "VerifyInput",
    "VerifyResult",
    "ProcessRegistry",
    "ProcessRunner",
    "ExecutionContext",
    "StrategySlot",
    "collect_strategy_slots",
    "collect_strategy_types",
    "default_strategies",
]
