"""後方互換 re-export — xkep_cae.core から re-export.

process/ の実体は core/ に移動済み。
既存コードの ``from xkep_cae.process import ...`` を壊さないための互換レイヤー。
"""

from xkep_cae.core import (  # noqa: F401
    AbstractProcess,
    AssembleCallbacks,
    BatchProcess,
    BoundaryData,
    CompatibilityProcess,
    ContactFrictionInputData,
    ContactSetupData,
    ExecutionContext,
    MeshData,
    NodeType,
    PostProcess,
    PreProcess,
    ProcessMeta,
    ProcessMetaclass,
    ProcessNode,
    ProcessRegistry,
    ProcessRunner,
    ProcessTree,
    SolverProcess,
    SolverResultData,
    SolverStrategies,
    StrategySlot,
    VerifyInput,
    VerifyProcess,
    VerifyResult,
    binds_to,
    collect_strategy_slots,
    collect_strategy_types,
    default_strategies,
)

__all__ = [
    "AbstractProcess",
    "ProcessMeta",
    "ProcessMetaclass",
    "PreProcess",
    "SolverProcess",
    "PostProcess",
    "VerifyProcess",
    "BatchProcess",
    "CompatibilityProcess",
    "binds_to",
    "ProcessTree",
    "ProcessNode",
    "NodeType",
    "MeshData",
    "BoundaryData",
    "ContactSetupData",
    "AssembleCallbacks",
    "ContactFrictionInputData",
    "SolverResultData",
    "SolverStrategies",
    "VerifyInput",
    "VerifyResult",
    "ProcessRegistry",
    "ProcessRunner",
    "ExecutionContext",
    "StrategySlot",
    "collect_strategy_slots",
    "collect_strategy_types",
    "default_strategies",
]
